#dependencies:
#  - matplotlib==3.3.2
#  - networkx=2.4
#  - numpy==1.19.2
#  - pandas==1.1.3
#  - scipy==1.5.2
#  - tqdm==4.46.0
#  - watermark==2.0.2
#  - python-wget==3.2
#  - shapely
#  - Cartopy==0.18.0
#  - netCDF4
#  - pooch==1.2.0
#  - pint==0.16.1
#  - pyproj==2.6.1.post1
#  - traitlets==4.3.3
#  - xarray==0.16.1

dependencies:
  - python==3.6.7
  - matplotlib==3.2.2
  - networkx=2.4
  - numpy==1.18.5
  - pandas==1.1.0
  - scipy==1.5.2
  - tqdm==4.46.0
  - watermark==2.0.2
  - python-wget==3.2
  - shapely
  - Cartopy==0.18.0
  - xarray
  - netcdf4
  - pooch
  - pint
  - pyproj
  - traitlets
  - metpy=0.12.2
